FROM arm32v7/ubuntu:16.04

RUN apt-get update \
    && apt-get install -y \
    libboost-python-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3.5 \
    python3-pip \
    wget \
    inetutils-traceroute \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Repository of pre-built wheels for ARM
RUN echo '[global]' >> /etc/pip.conf && \
    echo 'extra-index-url=https://www.piwheels.org/simple' >> /etc/pip.conf

RUN pip3 install --upgrade pip 
RUN pip3 install --no-cache-dir https://modelmgmtreswcus.azureedge.net/wheels/azure_iothub_device_client-1.4.3-py3-none-linux_armv7l.whl

CMD python3 -u ./audiocapture.py